### PR TITLE
Add snap provider

### PR DESCRIPTION
**Pull request by achilleasa**
This PR contributes a snap-based package manager implementation and applies some drive-by improvements to this package.

The `NewPackageManager` has **not** been modified to return snap package manager instances; this is intentional.

First of all, clients must specify the channel and confinement preferences (can also be left empty to use the snap defaults) when creating a new snap package manager instance. Secondly, not all packages might be available as snaps; in this case, clients can call `NewPackageManager` to get back a package manager that can install those packages and then use `NewSnapPackageManager` to obtain a package manager that can install the ones available as snaps.

### CODE REVIEW

**Comment by mitechie** [comment]
!!build!!

**Comment by achilleasa** [comment]
$$merge$$

**Comment by mitechie** [comment]
!!build!!

**Comment by mitechie** [comment]
!!build!!

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
