### PR TITLE
Use system for proxy

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following uses system instead of core to set the proxy settings. The
reason for this change is to remove installing core when bootstrapping.
Originally thought it was required for installing mongo, it wasn't
infact it was used to change the proxy settings for the charm store.

See https://github.com/juju/packaging/pull/7 for the setup of proxying with the snap store.

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
I don't think Juju wants to use snaps directly before focal, right? In which case 2.32 supporting 'system' since bionic gives us reasonable confidence we don't have to do a version check to decide between system and core.

**Comment by jameinel** [comment]
(I guess that changes for 3.0 where we would use mongo from a snap on Xenial+, but at least our current cloud images look to be including much newer snapd versions (2.49 when I checked)). Which still makes this ok.

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
!!build!!

**Review by achilleasa — APPROVED** [review]
LGTM. Let's make sure that both bootstrap and `juju deploy --to:lxd` work as expected in bionic/focal when we pull the changes into juju (and also that the proxy updates work correctly).

**Comment by jameinel** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
